basic.forever(function () {
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOn)
    basic.pause(200)
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOff)
    basic.pause(200)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
    basic.pause(200)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOff)
    basic.pause(200)
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOn)
    basic.pause(200)
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOff)
    basic.pause(200)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
    basic.pause(200)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOff)
})
basic.forever(function () {
    music.playTone(330, music.beat(BeatFraction.Eighth))
})
basic.forever(function () {
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 255)
    basic.pause(200)
    maqueen.motorStop(maqueen.Motors.M1)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 255)
    basic.pause(200)
    maqueen.motorStop(maqueen.Motors.M2)
    basic.pause(200)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 255)
    basic.pause(200)
    maqueen.motorStop(maqueen.Motors.M1)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 255)
    basic.pause(200)
    maqueen.motorStop(maqueen.Motors.M2)
})
basic.forever(function () {
    led.plot(0, 0)
    basic.pause(200)
    led.unplot(0, 0)
    basic.pause(200)
    led.plot(1, 0)
    basic.pause(100)
    led.unplot(1, 0)
    basic.pause(200)
    led.plot(2, 0)
    basic.pause(200)
    led.unplot(2, 0)
    basic.pause(200)
    led.plot(3, 0)
    basic.pause(200)
    led.unplot(3, 0)
    basic.pause(200)
    led.plot(4, 0)
    basic.pause(200)
    led.unplot(4, 0)
    basic.pause(200)
    led.plot(5, 0)
    basic.pause(200)
    led.unplot(5, 0)
    basic.pause(200)
})
